first run of windows gha

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -58,7 +58,66 @@ jobs:
             ansible-playbook -e "ansible_python_interpreter=${{ matrix.ansible_python_interpreter }}" molecule/${{ matrix.scenario }}/playbook.yml
 
             echo "Test the results"
-            ansible-playbook -e "ansible_python_interpreter=${{ matrix.ansible_python_interpreter }}" tests/tests_macos_${{ matrix.scenario }}.yml
+            ansible-playbook -e "ansible_python_interpreter=${{ matrix.ansible_python_interpreter }}" tests/${{ matrix.scenario }}/macosx.yml
+
+            echo "Idempotence check"
+            idempotence=$(mktemp)
+            ansible-playbook -e "ansible_python_interpreter=${{ matrix.ansible_python_interpreter }}" molecule/${{ matrix.scenario }}/playbook.yml | tee -a ${idempotence}
+            tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
+          fi
+        env:
+          ANSIBLE_FORCE_COLOR: '1'
+          OBJC_DISABLE_INITIALIZE_FORK_SAFETY: 'YES'
+  windows:
+    name: windows
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        include: 
+          - os: windows-2019
+            ansible_python_interpreter: C:\Python310\python.exe
+        scenario:
+          - latest
+          - default
+          - alternative
+        ansible_version:
+          - "2.9"
+          - "2.10"
+          - "4.10"
+          - "5.1"
+
+    steps:
+      - name: Check out the codebase
+        uses: actions/checkout@v2
+
+      - name: Install ansible
+        run: pip.exe install "ansible~=${{ matrix.ansible_version }}.0"
+
+      - name: Set up the test environment
+        run: |
+          tests/test-inventory ./test-inventory
+          tests/ansible.cfg ./ansible.cfg
+          pip.exe install -r test-requirements.txt
+          mkdir 'C:\runner\.ansible\roles'
+          mklink /d $GITHUB_WORKSPACE 'C:\runner\.ansible\roles\cloudalchemy.node_exporter'
+
+      - name: playbook tests
+        run: |
+          if [[ -n "${{ github.event.pull_request.number }}" ]] && [[ "${{ matrix.scenario }}" == 'latest' ]]; then
+            echo "Not testing 'latest' and 'pull request'"
+          else
+            echo "Test the playbook's syntax"
+            ansible-playbook -e "ansible_python_interpreter=${{ matrix.ansible_python_interpreter }}" molecule/${{ matrix.scenario }}/playbook.yml --syntax-check
+
+            echo "Run the prepare playbook"
+            ansible-playbook -e "ansible_python_interpreter=${{ matrix.ansible_python_interpreter }}" molecule/${{ matrix.scenario }}/prepare.yml
+
+            echo "Run the main playbook"
+            ansible-playbook -e "ansible_python_interpreter=${{ matrix.ansible_python_interpreter }}" molecule/${{ matrix.scenario }}/playbook.yml
+
+            echo "Test the results"
+            ansible-playbook -e "ansible_python_interpreter=${{ matrix.ansible_python_interpreter }}" tests/${{ matrix.scenario }}/windows.yml
 
             echo "Idempotence check"
             idempotence=$(mktemp)
